// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0Zo1fHAoWpc34B3fwAWM0q6zuyBcLMw',
    appId: '1:815612292606:web:bb0028421be5ac99c224af',
    messagingSenderId: '815612292606',
    projectId: 'empapp-ee8eb',
    authDomain: 'empapp-ee8eb.firebaseapp.com',
    storageBucket: 'empapp-ee8eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOanNBL0PgnGNaNqzzvqeO4uJxqNj6AIk',
    appId: '1:815612292606:android:d9ff022dbce86774c224af',
    messagingSenderId: '815612292606',
    projectId: 'empapp-ee8eb',
    storageBucket: 'empapp-ee8eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBELdZyCOcQQmfB6CNTp2trrQJSxWHVQBQ',
    appId: '1:815612292606:ios:1f790f1e378443e5c224af',
    messagingSenderId: '815612292606',
    projectId: 'empapp-ee8eb',
    storageBucket: 'empapp-ee8eb.appspot.com',
    iosBundleId: 'com.example.empapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBELdZyCOcQQmfB6CNTp2trrQJSxWHVQBQ',
    appId: '1:815612292606:ios:1f790f1e378443e5c224af',
    messagingSenderId: '815612292606',
    projectId: 'empapp-ee8eb',
    storageBucket: 'empapp-ee8eb.appspot.com',
    iosBundleId: 'com.example.empapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo0Zo1fHAoWpc34B3fwAWM0q6zuyBcLMw',
    appId: '1:815612292606:web:4cbf354b8ab75cc2c224af',
    messagingSenderId: '815612292606',
    projectId: 'empapp-ee8eb',
    authDomain: 'empapp-ee8eb.firebaseapp.com',
    storageBucket: 'empapp-ee8eb.appspot.com',
  );

}